-- Create orders table to support tailoring workflow
-- Includes core fields used across services; OTP columns are added by add_otp_columns.sql
CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(50) NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `tailor_id` INT UNSIGNED NOT NULL,
  `service_type` VARCHAR(100) DEFAULT NULL,
  `garment_type` VARCHAR(100) DEFAULT NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT 1,
  `measurements` TEXT,
  `special_instructions` TEXT,
  `estimated_price` DECIMAL(10,2) DEFAULT 0.00,
  `final_price` DECIMAL(10,2) DEFAULT NULL,
  `order_status` VARCHAR(50) NOT NULL DEFAULT 'pending',
  `payment_status` VARCHAR(50) NOT NULL DEFAULT 'unpaid',
  `order_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `delivery_date` DATETIME DEFAULT NULL,
  `fabric_type` VARCHAR(100) DEFAULT NULL,
  `fabric_color` VARCHAR(50) DEFAULT NULL,
  `design_specifications` TEXT,
  `measurements_snapshot` TEXT,
  `measurement_id` INT UNSIGNED DEFAULT NULL,
  `deadline` DATE DEFAULT NULL,
  `first_fitting_date` DATETIME DEFAULT NULL,
  `final_fitting_date` DATETIME DEFAULT NULL,
  `deposit_amount` DECIMAL(10,2) DEFAULT 0.00,
  `deposit_paid_at` DATETIME DEFAULT NULL,
  `balance_due` DECIMAL(10,2) DEFAULT 0.00,
  `alteration_notes` TEXT,
  `alteration_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `source_order_id` INT UNSIGNED DEFAULT NULL,
  `completed_at` DATETIME DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_order_number` (`order_number`),
  KEY `idx_customer_status` (`customer_id`, `order_status`),
  KEY `idx_tailor_status` (`tailor_id`, `order_status`),
  KEY `idx_deadline_status` (`deadline`, `order_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
