module.exports = (sequelize, DataTypes) => {
  const Order = sequelize.define(
    'Order',
    {
      id: { type: DataTypes.INTEGER.UNSIGNED, autoIncrement: true, primaryKey: true },
      order_number: { type: DataTypes.STRING(50), allowNull: false, unique: true },
      customer_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
      tailor_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
      service_type: { type: DataTypes.STRING(100) },
      garment_type: { type: DataTypes.STRING(100) },
      quantity: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 1 },
      measurements: { type: DataTypes.TEXT },
      special_instructions: { type: DataTypes.TEXT },
      estimated_price: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0 },
      final_price: { type: DataTypes.DECIMAL(10, 2) },
      order_status: { type: DataTypes.STRING(50), allowNull: false, defaultValue: 'pending' },
      start_otp: { type: DataTypes.STRING(6) },
      start_otp_verified_at: { type: DataTypes.DATE },
      delivery_otp: { type: DataTypes.STRING(6) },
      delivery_otp_verified_at: { type: DataTypes.DATE },
      payment_status: { type: DataTypes.STRING(50), allowNull: false, defaultValue: 'unpaid' },
      order_date: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
      delivery_date: { type: DataTypes.DATE },
      fabric_type: { type: DataTypes.STRING(100) },
      fabric_color: { type: DataTypes.STRING(50) },
      design_specifications: { type: DataTypes.TEXT },
      measurements_snapshot: { type: DataTypes.TEXT },
      measurement_id: { type: DataTypes.INTEGER.UNSIGNED },
      deadline: { type: DataTypes.DATEONLY },
      first_fitting_date: { type: DataTypes.DATE },
      final_fitting_date: { type: DataTypes.DATE },
      deposit_amount: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0 },
      deposit_paid_at: { type: DataTypes.DATE },
      balance_due: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0 },
      alteration_notes: { type: DataTypes.TEXT },
      alteration_count: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
      source_order_id: { type: DataTypes.INTEGER.UNSIGNED },
      completed_at: { type: DataTypes.DATE },
      created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
      updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    },
    {
      tableName: 'orders',
      timestamps: true,
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    }
  );

  return Order;
};
